/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modeloqytetet.Calle;
import modeloqytetet.MetodoSalirCarcel;
import modeloqytetet.Qytetet;
import modeloqytetet.TipoCasilla;

/**
 *
 * @author david
 */
public class ControladorQytetet extends javax.swing.JFrame {
    private static Qytetet modeloQytetet; 

    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();        
    }
    
    public void actualizar(Qytetet qytetet) {
        modeloQytetet = qytetet;
        this.repaint();
        this.revalidate();
    }

    
    public void habilitarComenzarTurno(){
        this.jComprarPropiedad.setEnabled(false);
        this.jSiguienteJugador.setEnabled(false);
        this.jAplicarSorpresa.setEnabled(false);
        this.jGestionInmobiliaria.setEnabled(false);
        
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.jSalirCarcelPagando.setEnabled(true);
            this.jSalirCarcelDado.setEnabled(true);
        }
        else
            this.jJugar.setEnabled(true);
        
        this.vistaQytetet.limpiarPanelCartaSorpresa();
        this.vistaQytetet.gestionInmobiliaria("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaQytetet = new GUIQytetet.VistaQytetet();
        jSalirCarcelDado = new javax.swing.JButton();
        jSalirCarcelPagando = new javax.swing.JButton();
        jJugar = new javax.swing.JButton();
        jComprarPropiedad = new javax.swing.JButton();
        jAplicarSorpresa = new javax.swing.JButton();
        jSiguienteJugador = new javax.swing.JButton();
        jGestionInmobiliaria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSalirCarcelDado.setText("Salir Cárcel Dado");
        jSalirCarcelDado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSalirCarcelDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirCarcelDadoActionPerformed(evt);
            }
        });

        jSalirCarcelPagando.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSalirCarcelPagando.setLabel("Salir Cárcel Pagando");
        jSalirCarcelPagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirCarcelPagandoActionPerformed(evt);
            }
        });

        jJugar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jJugar.setText("Jugar");
        jJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJugarActionPerformed(evt);
            }
        });

        jComprarPropiedad.setText("Comprar propiedad");
        jComprarPropiedad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComprarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComprarPropiedadActionPerformed(evt);
            }
        });

        jAplicarSorpresa.setText("Aplicar sorpresa");
        jAplicarSorpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAplicarSorpresaActionPerformed(evt);
            }
        });

        jSiguienteJugador.setText("Siguiente jugador");
        jSiguienteJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSiguienteJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSiguienteJugadorActionPerformed(evt);
            }
        });

        jGestionInmobiliaria.setText("Gestión inmobiliaria");
        jGestionInmobiliaria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jGestionInmobiliaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGestionInmobiliariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSalirCarcelDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSalirCarcelPagando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(jJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComprarPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGestionInmobiliaria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jAplicarSorpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSiguienteJugador)
                .addContainerGap())
            .addComponent(vistaQytetet, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComprarPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jGestionInmobiliaria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jJugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSalirCarcelDado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSalirCarcelPagando, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSiguienteJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAplicarSorpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirCarcelDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirCarcelDadoActionPerformed
        boolean resultado =
                modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
        this.jSalirCarcelDado.setEnabled(false);
        this.jSalirCarcelPagando.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.jJugar.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.jSiguienteJugador.setEnabled(true);
        }
        this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_jSalirCarcelDadoActionPerformed

    private void jSiguienteJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSiguienteJugadorActionPerformed
        if(modeloQytetet.getJugadorActual().getSaldo() <= 0){
            this.jJugar.setEnabled(false);
            this.jSiguienteJugador.setEnabled(false);
            this.jGestionInmobiliaria.setEnabled(false);
            this.vistaQytetet.finJuego();
            JOptionPane.showMessageDialog(this, modeloQytetet.obtenerRanking());
            this.dispose();
        }
        
        modeloQytetet.siguienteJugador();
        this.habilitarComenzarTurno();        
        this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_jSiguienteJugadorActionPerformed

    private void jSalirCarcelPagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirCarcelPagandoActionPerformed
        boolean resultado = 
                modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.jSalirCarcelPagando.setEnabled(false);
        this.jSalirCarcelDado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.jJugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.jSiguienteJugador.setEnabled(true);
        }
        
        this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_jSalirCarcelPagandoActionPerformed

    private void jJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJugarActionPerformed
        this.jSalirCarcelPagando.setEnabled(false);
        this.jSalirCarcelDado.setEnabled(false);
        this.habilitarComenzarTurno();
        this.jJugar.setEnabled(false);
        
        if(modeloQytetet.getJugadorActual().getSaldo() > 0){
            boolean noTienePropietario = !(modeloQytetet.jugar());
            this.vistaQytetet.actualizar(modeloQytetet);
            if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.CALLE) {
                if (noTienePropietario)
                    this.jComprarPropiedad.setEnabled(true);

                this.jSiguienteJugador.setEnabled(true);
            }else if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.SORPRESA) {
                this.vistaQytetet.actualizar(modeloQytetet);
                this.vistaQytetet.mostrarCartaSorpresa(modeloQytetet);

                this.jSiguienteJugador.setEnabled(false);
                this.jGestionInmobiliaria.setEnabled(false);
                this.jAplicarSorpresa.setEnabled(true);
            }
            else
                this.jSiguienteJugador.setEnabled(true);
        }
        if(modeloQytetet.getJugadorActual().tengoPropiedades())
            this.jGestionInmobiliaria.setEnabled(true);
        
        this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_jJugarActionPerformed

    private void jComprarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComprarPropiedadActionPerformed
        boolean puedoComprarPropiedad = modeloQytetet.comprarTituloPropiedad();
        if(!puedoComprarPropiedad)
            JOptionPane.showMessageDialog(this, "¡No puedes comprar la calle!");
        else
            this.jGestionInmobiliaria.setEnabled(true);
        
        this.jComprarPropiedad.setEnabled(false);
        
        this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_jComprarPropiedadActionPerformed

    private void jAplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAplicarSorpresaActionPerformed
        boolean noTienePropietario = !(modeloQytetet.aplicarSorpresa());
        if(modeloQytetet.getJugadorActual().getSaldo() > 0){
            if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.CALLE)
                if (noTienePropietario)
                    this.jComprarPropiedad.setEnabled(true);
        }
        
        this.jAplicarSorpresa.setEnabled(false);
        this.jSiguienteJugador.setEnabled(true);
        if (!modeloQytetet.getJugadorActual().getEncarcelado() && 
                modeloQytetet.getJugadorActual().getSaldo() > 0 && 
                modeloQytetet.getJugadorActual().tengoPropiedades())
            this.jGestionInmobiliaria.setEnabled(true);
        
        this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_jAplicarSorpresaActionPerformed
    
    private void jGestionInmobiliariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionInmobiliariaActionPerformed
        this.vistaQytetet.gestionInmobiliaria(" ");
        if (modeloQytetet.getJugadorActual().getSaldo() > 0 &&
                modeloQytetet.getJugadorActual().tengoPropiedades()) {
            SeleccionarOpcionInmobiliaria opcionInmobiliaria 
            = new SeleccionarOpcionInmobiliaria(this, rootPaneCheckingEnabled);
            opcionInmobiliaria.setVisible(true);

            int opcion = opcionInmobiliaria.obtenerOpcion();
            Calle opcionCasilla = null;
            ArrayList<Calle> misPropiedades = new ArrayList();

            if (opcion==1 || opcion==2 || opcion==3 || opcion==4)
                misPropiedades = modeloQytetet.propiedadesHipotecadasJugador(false);
            else if (opcion==5 )
                misPropiedades = modeloQytetet.propiedadesHipotecadasJugador(true);

            if(opcion != 0){
                String[] prop = new String[12];
                int i = 0;
                for (Calle c : misPropiedades) {
                    prop[i] = c.getTitulo().getNombre();
                    i++;
                }

                PanelPropiedades panel = new PanelPropiedades(this, rootPaneCheckingEnabled);
                panel.setModel(new javax.swing.DefaultComboBoxModel(prop));
                panel.setVisible(true);

                for(Calle c : misPropiedades)
                    if(panel.obtenerPropiedad().equals(c.getTitulo().getNombre()))
                        opcionCasilla = c;

            }
            if(opcionCasilla != null)
                switch (opcion) {
                    case 1:
                        boolean puedoEdificarCasa = modeloQytetet.edificarCasa(opcionCasilla);
                        if(puedoEdificarCasa)
                            vistaQytetet.gestionInmobiliaria("Has edificado una casa");
                        else
                            vistaQytetet.gestionInmobiliaria("¡No puedes edificar ninguna casa!");
                        break;
                    case 2: 
                        boolean puedoEdificarHotel = modeloQytetet.edificarHotel(opcionCasilla);
                        if(puedoEdificarHotel)
                            vistaQytetet.gestionInmobiliaria("Has edificado un hotel");
                        else
                            vistaQytetet.gestionInmobiliaria("¡No puedes edificar ningún hotel!");
                        break;
                    case 3: 
                        boolean puedoVenderPropiedad = modeloQytetet.venderPropiedad(opcionCasilla);
                        if(puedoVenderPropiedad)
                            vistaQytetet.gestionInmobiliaria("Has vendido la propiedad");
                        else
                            vistaQytetet.gestionInmobiliaria("¡No puedes vender la propiedad!");
                        break;
                    case 4:
                        boolean puedoHipotecarPropiedad = modeloQytetet.hipotecarPropiedad(opcionCasilla);
                        if(puedoHipotecarPropiedad)
                            vistaQytetet.gestionInmobiliaria("Has hipotecado la propiedad");
                        else
                            vistaQytetet.gestionInmobiliaria("¡No puedes hipotecar la propiedad!");
                        break;
                    case 5:
                        boolean puedoCancelarHipoteca = modeloQytetet.cancelarHipoteca(opcionCasilla);
                        if(puedoCancelarHipoteca)
                            vistaQytetet.gestionInmobiliaria("Has cancelado la hipoteca");
                        else
                            vistaQytetet.gestionInmobiliaria("¡No cancelar la hipoteca!");
                        break;
                    default : 
                        break;
                }
                
        }
        vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_jGestionInmobiliariaActionPerformed


    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ControladorQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ControladorQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ControladorQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ControladorQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ControladorQytetet().setVisible(true);
//            }
//        });
//    }
    public static void main(String[] args){
        ControladorQytetet controladorQytetet = new ControladorQytetet();
        
        CapturaNombreJugadores capturaNombres = 
                new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres = capturaNombres.obtenerNombres();
        Dado.createInstance(controladorQytetet);
        
        modeloQytetet = Qytetet.getInstance();        
        modeloQytetet.inicializarJuego(nombres);

        controladorQytetet.setVisible(true); //Esta debe ser la última
    //línea de código del main
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAplicarSorpresa;
    private javax.swing.JButton jComprarPropiedad;
    private javax.swing.JButton jGestionInmobiliaria;
    private javax.swing.JButton jJugar;
    private javax.swing.JButton jSalirCarcelDado;
    private javax.swing.JButton jSalirCarcelPagando;
    private javax.swing.JButton jSiguienteJugador;
    private GUIQytetet.VistaQytetet vistaQytetet;
    // End of variables declaration//GEN-END:variables
}

