/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

/**
 *
 * @author david
 */
public class SeleccionarOpcionInmobiliaria extends javax.swing.JDialog {
    private int opcion;
    /**
     * Creates new form SeleccionarOpcionInmobiliaria
     */
    public SeleccionarOpcionInmobiliaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(250, 250);
        jEdificarCasa.setSelected(true);
        this.opcion = 0;
    }
    
    public int obtenerOpcion() {
        return opcion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGrupo = new javax.swing.ButtonGroup();
        jEdificarCasa = new javax.swing.JRadioButton();
        jEdificarHotel = new javax.swing.JRadioButton();
        jVenderPropiedad = new javax.swing.JRadioButton();
        jAceptar = new javax.swing.JButton();
        jCancelarHipoteca = new javax.swing.JRadioButton();
        jHipotecarPropiedad = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonGrupo.add(jEdificarCasa);
        jEdificarCasa.setText("Edificar casa");
        jEdificarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdificarCasaActionPerformed(evt);
            }
        });

        botonGrupo.add(jEdificarHotel);
        jEdificarHotel.setText("Edificar hotel");

        botonGrupo.add(jVenderPropiedad);
        jVenderPropiedad.setText("Vender propiedad");
        jVenderPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVenderPropiedadActionPerformed(evt);
            }
        });

        jAceptar.setText("Aceptar");
        jAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });

        botonGrupo.add(jCancelarHipoteca);
        jCancelarHipoteca.setText("Cancelar  hipoteca");

        botonGrupo.add(jHipotecarPropiedad);
        jHipotecarPropiedad.setText("Hipotecar propiedad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jVenderPropiedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEdificarHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEdificarCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAceptar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCancelarHipoteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jHipotecarPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEdificarCasa)
                .addGap(18, 18, 18)
                .addComponent(jEdificarHotel)
                .addGap(18, 18, 18)
                .addComponent(jVenderPropiedad)
                .addGap(18, 18, 18)
                .addComponent(jHipotecarPropiedad)
                .addGap(18, 18, 18)
                .addComponent(jCancelarHipoteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEdificarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdificarCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEdificarCasaActionPerformed

    private void jVenderPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVenderPropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVenderPropiedadActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        if (jEdificarCasa.isSelected()) {
            opcion = 1;
        } else if (jEdificarHotel.isSelected()) {
            opcion = 2;
        } else if (jVenderPropiedad.isSelected()) {
            opcion = 3;
        } else if (jHipotecarPropiedad.isSelected()) {
            opcion = 4;
        } else if (jCancelarHipoteca.isSelected()) {
            opcion = 5;
        }

        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionarOpcionInmobiliaria dialog = new SeleccionarOpcionInmobiliaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonGrupo;
    private javax.swing.JButton jAceptar;
    private javax.swing.JRadioButton jCancelarHipoteca;
    private javax.swing.JRadioButton jEdificarCasa;
    private javax.swing.JRadioButton jEdificarHotel;
    private javax.swing.JRadioButton jHipotecarPropiedad;
    private javax.swing.JRadioButton jVenderPropiedad;
    // End of variables declaration//GEN-END:variables
}
