/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

/**
 *
 * @author david
 */
public class VistaCartaSorpresa extends javax.swing.JPanel {

    /**
     * Creates new form VistaCartaSorpresa
     */
    public VistaCartaSorpresa() {
        initComponents();
    }
    
    public void actualizar(String descripcionCasilla){
        this.jtTextoCartaSorpresa.setText(descripcionCasilla);
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtTextoCartaSorpresa = new javax.swing.JTextArea();

        jtTextoCartaSorpresa.setEditable(false);
        jtTextoCartaSorpresa.setBackground(new java.awt.Color(235, 253, 255));
        jtTextoCartaSorpresa.setColumns(20);
        jtTextoCartaSorpresa.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jtTextoCartaSorpresa.setRows(5);
        jtTextoCartaSorpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carta sorpresa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(31, 145, 211))); // NOI18N
        jtTextoCartaSorpresa.setName("Carta sorpresa"); // NOI18N
        jScrollPane1.setViewportView(jtTextoCartaSorpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jtTextoCartaSorpresa;
    // End of variables declaration//GEN-END:variables
}
