/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import modeloqytetet.Qytetet;

/**
 *
 * @author david
 */
public class VistaQytetet extends javax.swing.JPanel {

    /**
     * Creates new form VistaQytetet
     */
    public VistaQytetet() {
        initComponents();
    }
    /*Ve ahora a la pestaña “Source” y define el método actualizar que recibirá como argumento un
objeto de la clase Qytetet. El cometido de este método será actualizar las tres vistas con los
datos del jugador actual, la casilla actual de dicho jugador y la carta actual de qytetet. Ten en
cuenta que si la carta actual es null, deberá mostrarse una cadena vacía o un mensaje
indicando que no hay carta.*/
    public void actualizar(Qytetet qytetet) {
        vistaJugador1.actualizar(qytetet.getJugadorActual().toString());
        vistaCasilla1.actualizar(qytetet.getJugadorActual().getCasillaActual().toString());
        
        this.repaint();
        this.revalidate();
    }
    
    public void limpiarPanelCartaSorpresa() {
        vistaCartaSorpresa1.actualizar("");
    }
    
    public void mostrarCartaSorpresa(Qytetet qytetet) {
        if(qytetet.getCartaActual() != null)
            vistaCartaSorpresa1.actualizar(qytetet.getCartaActual().toString());
    }
    
    public void gestionInmobiliaria(String texto) {
        vistaGestionInmobiliaria2.actualizar(texto);
    }
    
    public void finJuego() {
        vistaJugador1.actualizar(" ");
        vistaCasilla1.actualizar(" \nFIN DEL JUEGO ");
        vistaCartaSorpresa1.actualizar(" ");
        vistaGestionInmobiliaria2.actualizar(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaCasilla1 = new GUIQytetet.VistaCasilla();
        vistaCartaSorpresa1 = new GUIQytetet.VistaCartaSorpresa();
        vistaGestionInmobiliaria2 = new GUIQytetet.VistaGestionInmobiliaria();
        vistaJugador1 = new GUIQytetet.VistaJugador();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vistaCasilla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vistaCartaSorpresa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vistaJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vistaGestionInmobiliaria2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vistaGestionInmobiliaria2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vistaJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vistaCartaSorpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIQytetet.VistaCartaSorpresa vistaCartaSorpresa1;
    private GUIQytetet.VistaCasilla vistaCasilla1;
    private GUIQytetet.VistaGestionInmobiliaria vistaGestionInmobiliaria2;
    private GUIQytetet.VistaJugador vistaJugador1;
    // End of variables declaration//GEN-END:variables
}
