/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

/**
 *
 * @author david
 */
public class VistaGestionInmobiliaria extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestionInmobiliaria
     */
    public VistaGestionInmobiliaria() {
        initComponents();
    }
    
    public void actualizar(String descripcionCasilla){
        this.jGestionInmobiliaria.setText(descripcionCasilla);
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jGestionInmobiliaria = new javax.swing.JTextArea();

        jGestionInmobiliaria.setEditable(false);
        jGestionInmobiliaria.setBackground(new java.awt.Color(253, 253, 223));
        jGestionInmobiliaria.setColumns(20);
        jGestionInmobiliaria.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jGestionInmobiliaria.setRows(5);
        jGestionInmobiliaria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión inmobiliaria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(183, 177, 5))); // NOI18N
        jScrollPane1.setViewportView(jGestionInmobiliaria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jGestionInmobiliaria;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
